### ISSUE TITLE
How can i open the origin album

### ISSUE THREAD

**Issue by benladen** [Reisyukaku/ReiNX#106]
Hello. I use 2.0, and how can i open the origin album, thx.
I hold R open it, and go into hbl, too.
My switch system version is 5.1 now.

**Comment by Reisyukaku** [comment]
Did you try L?

**Comment by benladen** [comment]
> Did you try L?

yes, including l+r, zr and zl :(

**Comment by Reisyukaku** [comment]
I'll see if its a bug. That should normally work.

**Comment by friedkeenan** [comment]
Back when I was on ReiNX, I couldn't open the album normally when I had the hbl.nsp, so maybe the logic was never added for that?

**Comment by Reisyukaku** [comment]
ill mark this as a bug

**Comment by Brawl345** [comment]
Yeah the loader.ini support seems to be missing? In the meantime you can use the legacy HBL: https://reinx.guide/guide/download-and-install and the config that's linked there.

**Comment by Endar-Marit** [comment]
Use the legacy method to open the album.

https://reinx.guide/troubleshooting
