### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by goooodlife** [Reisyukaku/ReiNX#107]
excuse me, I want to know how to turn on debug mode.
Edit the configuration file?

**Comment by Reisyukaku** [comment]
Debug mode? as in debug svc?
if its debug svc then create a empty file called 'debug' in /Reinx folder

**Comment by goooodlife** [comment]
Thanks for the answer,I succeede. But if entering sleep mode，switch cannot be woken up

**Comment by Reisyukaku** [comment]
yea, thats a side effect of debug on 6.0+  at the moment

**Comment by goooodlife** [comment]
Thank you for answering, I have been using reinx, I like it very much.
although Programming is very hard, Keep up the good work, and very looking forward to cheat
