### ISSUE TITLE
error code: 0x00299002

### ISSUE THREAD

**Issue by JohnChancfz** [Reisyukaku/ReiNX#111]
failed to install NSP!
error code: 0x00299002

**Comment by lavaJockey** [comment]
What are you using to install nsps?

**Comment by Solcodeguy** [comment]
I'm using tinfoil and I tried using goldleaf.. nsp error failed to open meta nca

**Comment by lavaJockey** [comment]
Newest Goldleaf fixes all the 7.0.X problems. So I think it should work now!

**Comment by Solcodeguy** [comment]
Do you have a link or the version of goldleaf I should download?

SaM

**Comment by lavaJockey** [comment]
https://github.com/XorTroll/Goldleaf/releases/tag/0.5
