### ISSUE TITLE
Can't load cfw from source...

### ISSUE THREAD

**Issue by lavaJockey** [Reisyukaku/ReiNX#113]
When I built the source of ReiNX it just shows the splash then crashes. I am guessing this has to do with the source not including sept.

**Comment by Reisyukaku** [comment]
Yes, I have no plans on including that. This is the CFW repo and the sept mechanic is grabbed seperately. We dont do anything different in the sept we use so you can grab it from anywhere. Just remember to replace the /sept/payload.bin with reinx.bin named as 'payload.bin'

**Comment by lavaJockey** [comment]
Thanks! I did include Sept before I posted this but I did not realize you need to replace the payload.bin with the reinx.bin! Thank You So Much!
