### ISSUE TITLE
Feature: Add dev/debug ReiNX mode

### ISSUE THREAD

**Issue by tantoinet** [Reisyukaku/ReiNX#118]
instead of commenting out the debug messages, it may be better to create a debug mode and print them.
Those are useful for troubleshooting :)

**Comment by Reisyukaku** [comment]
What do you mean? we dont comment out debug messages.. all debug messages are available if you boot in verbose mode.

**Comment by tantoinet** [comment]
Some comments like [here](https://github.com/Reisyukaku/ReiNXToolkit/blob/master/source/Tools/autorcm.cpp) are useful for debug/advanced users.
It may be a good plan to allow users enabling a debug mode to see them

**Comment by Reisyukaku** [comment]
Thats the toolkit. A completely separate project.
