### ISSUE TITLE
Atmosphere 'sept' Compatibility

### ISSUE THREAD

**Issue by xTrM-EN** [Reisyukaku/ReiNX#119]
To use ReiNX on FW 7.0.0, it needs the sept folder.

The problem is that Atmosphere (and/or other CFWs) also uses that sept folder, with a different payload.bin file.
That means it's impossible to have 2 CFW on the same SD Card on 7.0.0 (works on 5.1.0 tho)

Is there a way to move the ReiNX used sept folder/payload into the ReiNX folder?

**Comment by Reisyukaku** [comment]
1) Im not sure why you'd ever need to use multiple cfw. That's just silly
2) No, we cant move anything. I asked scires if he'd be willing to fix this by giving us a custom sept but he denied it.
