### ISSUE TITLE
Uhh...

### ISSUE THREAD

**Issue by lavaJockey** [Reisyukaku/ReiNX#120]
I was comparing ReiNX 2.1.1 release [Left] and ReiNX built from latest source [Right]
![image](https://user-images.githubusercontent.com/31358302/56087691-08322c80-5e3e-11e9-8e1a-50d92fd5657c.png)
And it's not the same
P.S. red means file has different code

**Comment by fgsfdsfgs** [comment]
Binaries built from the same source generally will not be the same byte-for-byte, unless you employ deterministic compilation.

**Comment by lavaJockey** [comment]
Alright! Thanks for letting me know!
