### ISSUE TITLE
Can't launch album.

### ISSUE THREAD

**Issue by ir1descent** [Reisyukaku/ReiNX#121]
Using kosmos, then putting all the reinx files (Sept,reinx,..) on SD card and using the reinx bin.

Normal press album doesn't work. R+ press doesn't work.

Help?

**Comment by Endar-Marit** [comment]
Use the legacy method as described in the guide

https://reinx.guide/troubleshooting

**Comment by MUGIWARA93** [comment]
Can't launch álbum in the New release 2.2

**Comment by MUGIWARA93** [comment]
Just put in on the hbl.nsp in ReiNX folder.
