### ISSUE TITLE
8.0

### ISSUE THREAD

**Issue by melsbacksfriend** [Reisyukaku/ReiNX#122]
I'm using the latest nightly build and I'm on 8.0 and I can't boot into cfw.  any fixes?  My switch isn't patched.  I know because it gets stuck on this logo when I try booting.  
![20190420_095829](https://user-images.githubusercontent.com/36408599/56458983-3ab6ba80-6353-11e9-8938-0f3b1fa63117.jpg)

**Comment by Reisyukaku** [comment]
8.0 isnt fully implemented, hence no release and also only commit was "partial"

**Comment by melsbacksfriend** [comment]
Thanks for letting me know.  I'll downgrade now.
