### ISSUE TITLE
Error: Code 2000-0000 (0x0)

### ISSUE THREAD

**Issue by dothackjhe** [Reisyukaku/ReiNX#124]
I just updated to firmware 8.0.0 and, while using files for ReiNX 2.2, I encounter this weird bug. 

![IMG_20190424_093515](https://user-images.githubusercontent.com/18740174/56626685-4f59c200-6675-11e9-9602-17a7c4a60480.jpg)

**Comment by Reisyukaku** [comment]
Are you using a custom theme? maybe its broken?

**Comment by dothackjhe** [comment]
Yes, I am. I used NXThemesInstaller for it. 

How do I disable it?

**Comment by dothackjhe** [comment]
I managed to fix it by deleting a certain folder which contains the custom theme files within the "titles" folder in "reinx" folder.
