### ISSUE TITLE
Missing sigpatches probably

### ISSUE THREAD

**Issue by RetroGamer74** [Reisyukaku/ReiNX#125]
Try: Mario Kart 8 Deluxe. => Can not start the software. Please try again from the HOME menu.

Tested in AMS with sigpatches => OK.

**Comment by Peronia** [comment]
Yes, 50% of my games doesnt work anymore. I can confirm that.

**Comment by jit06** [comment]
I confirm too, I only have one game working

**Comment by Reisyukaku** [comment]
No, all the same patches are there.. I explained in #128
