### ISSUE TITLE
Games must update 

### ISSUE THREAD

**Issue by Peronia** [Reisyukaku/ReiNX#127]
When I try to start a game with update, a screen pops up.
Make update or cancel, I cant start the game without update. 
Reinx 2.2 and 8.0.1

**Comment by Reisyukaku** [comment]
see #128

**Comment by Peronia** [comment]
Even with this [comment](https://github.com/Reisyukaku/ReiNX/issues/129#issuecomment-487401305), its inpossible to play such games they need an update. I tried it with zelda. No option to just play the game. I can update it or cancel.

**Comment by Reisyukaku** [comment]
are you sure you replaced the old one? .. try redownloading the release

**Comment by Peronia** [comment]
I will try it later. With 6.2 and reinx 2.1 all was fine. You mean the 2.2 release?

**Comment by Reisyukaku** [comment]
I think thats normal though.
