### ISSUE TITLE
Trying to play any games does not work.

### ISSUE THREAD

**Issue by Tomo4** [Reisyukaku/ReiNX#128]
Whenever I try to play a game, it tells me "Unable to start software. Return to the HOME Menu and try again." I am on OFW 8.0.1 and using ReiNX 2.2.

**Comment by Reisyukaku** [comment]
game patches are still being fleshed out. Naturally nintendo added extra mitigation.

**Comment by Reisyukaku** [comment]
https://github.com/Reisyukaku/ReiNX/issues/129#issuecomment-487401305
