### ISSUE TITLE
game doesn't open, requires internet connection to run.

### ISSUE THREAD

**Issue by MUGIWARA93** [Reisyukaku/ReiNX#129]
install two games and both asked to disable the airplane mode and then asked to connect to the internet to open it, installed well and so far is stable, the only thing is to connect to internet with all games.

**Comment by MUGIWARA93** [comment]
![IMG-20190427-WA0033](https://user-images.githubusercontent.com/45437031/56853631-33158980-68f0-11e9-8125-cd46988d8b8c.jpg)
![IMG-20190427-WA0034](https://user-images.githubusercontent.com/45437031/56853637-41fc3c00-68f0-11e9-810a-6773361c19e9.jpg)
![IMG-20190427-WA0106](https://user-images.githubusercontent.com/45437031/56853644-56d8cf80-68f0-11e9-94a6-443df979d213.jpg)


I clarify that I already have the dns changed and I am in 8.0.1 with ReiNX 2.2.1

**Comment by Reisyukaku** [comment]
Fixed. Download the new rxp and replace the one in the patches folder.
