### ISSUE TITLE
8.0.1 , reinx2.2.1 sleep mode 

### ISSUE THREAD

**Issue by rijachung28** [Reisyukaku/ReiNX#131]
my switch version  : 8.0.1
reinx version           : 2.2.1 lastest build

1. press power button, and press again . But it did not wake up.

2. touch sleep mode button. and press power button.  But it did not wake up.

thankyou . be happy

**Comment by Reisyukaku** [comment]
Sleep mode was fixed already. I suppose you can try this build.
https://reinx.guide/downloads/ReiNX_v2.2.1.zip

**Comment by rijachung28** [comment]
it's work.
thanks you.
