### ISSUE TITLE
No album function

### ISSUE THREAD

**Issue by fergatr0n** [Reisyukaku/ReiNX#132]
No matter what I do, cannot load the default album. Am using the legacy homebrew menu and have deleted the nsp from ReiNX folder. There's no ini file created in the config folder to allow editing of functionality.

Is this a known issue and if so will the functionality be reimplemented in the future?

**Comment by Endar-Marit** [comment]
You need to have the latest legacy files for ReiNX (get them from the guide)

You cannot have hbl.nsp in the reinx at the same time

**Comment by Endar-Marit** [comment]
update, the new versions using hbl.nsp you use r to access hbmenu and not to access album
