### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by EmreBlkaya** [Reisyukaku/ReiNX#141]
i follow the guide but when i try to open album nothing happen (i try with Rcm Loader btw)

**Comment by NoyTheBiche** [comment]
ReiNX's Discord has a fix for HBL, you can download the fix [here](https://cdn.discordapp.com/attachments/548845841306091520/591663817835151380/ReiNX_2.4_Fixed.zip)

**Comment by EmreBlkaya** [comment]
> ReiNX's Discord has a fix for HBL, you can download the fix [here](https://cdn.discordapp.com/attachments/548845841306091520/591663817835151380/ReiNX_2.4_Fixed.zip)

thank you, i will try
