### ISSUE TITLE
Lack of support for 9.0.0

### ISSUE THREAD

**Issue by lululombard** [Reisyukaku/ReiNX#148]
Hi!
As far as I'm aware, ReiNX doesn't support the Switch OS 9.0.0. 
Is there any plans to update it?
Thanks!

**Comment by Cawluni** [comment]
Elise has uploaded a commit for 9.0 support.

However due to a rewrite, SysModules are currently broken. But it works. If you want to use sysModules, I would recommend using Kosmos as a temporary.

**Comment by Reisyukaku** [comment]
pointless issues pointing out the obvious. We'll get to it when we have time.
