### ISSUE TITLE
Sigpatches

### ISSUE THREAD

**Issue by ghost** [Reisyukaku/ReiNX#156]
If I'm right :
KOSMOS patches (dead) supported nocmac patches, fs_patches, ACID patches es_patches
NEUTOS (dead) supported fs_patches, ACID patches and es_patches
HarukoNX PKG2 patches still support fs_patches, ACID patches and es_patches 

So which patches are suppoted in ReiNX?
If you wantto support other patches, I've still a backup NEUTOS and Kosmos patches on my computer, and HarukoNX PKG2 patches are still availableon GitHub.

**Comment by D3fau4** [comment]
you dont need other patches because they are already included in the system but in any case, the exefs patches goes in: `/ReiNX/patches/`

**Comment by ghost** [comment]
Maybe yes, because you can only launch ReiNX trough FuséeGelée and not Hekate, so fr supporting Hekate, you would need ACID patches, nocmac patches (really usefull) and fs_patches.
