### ISSUE TITLE
Bitmap Splashes

### ISSUE THREAD

**Issue by Reisyukaku** [Reisyukaku/ReiNX#23]
Implement a transformation function to read bitmaps into frame buffer. Issue is making one that isnt noticeably slow.

**Comment by elephantp** [comment]
Question, if `splash.bin` and `splash.bmp` are both in folder, which one to use?

**Comment by neonsea** [comment]
The BMP loader I'm currently writing tries the .bmp first and falls back to .bin if that fails, and finally falls back to no splash if .bin is missing.

**Comment by Reisyukaku** [comment]
i kinda want this in homebrew instead
