### ISSUE TITLE
SD mount false return makes Switch hang

### ISSUE THREAD

**Issue by kizoLeonardoMontiel** [Reisyukaku/ReiNX#30]
Honestly a minor nitpick, but when you try to inject the ReiNx payload and forget to insert the SD card the Switch just hangs and you have to hard reset it.

I'd like to suggest you change the following piece of code to loop until the payload is injected instead:
`if (!sd_mount()){
 error("Failed to init SD card); 
 return;
}
`

Thank you so much for all the hard work in ReiNX :)

**Comment by HugoOdaX** [comment]
This happened to me a lot of times, but it isn't that annoying
