### ISSUE TITLE
Dragon Ball xenoverse 2 freezes up

### ISSUE THREAD

**Issue by vaccarieli** [Reisyukaku/ReiNX#37]
Whenever i play dragon ball xenoverse 2, it freezes my swith up, example i go to the option of eshop, or if i select to conect online, it freezes up as well i have reinstalled it from scratch, i am using reinx V2.

**Comment by Reisyukaku** [comment]
version 1.2?
Do you have multiple DLC?

**Comment by vaccarieli** [comment]
Sorry i am using V 1.2 yes, and i have installed all 9 Dlc, when i play is ok, but when my kid is playing by mistake he goes into nintendo eshop, and freezes.
Or even when i just start the game, you know that in the main screen it tells if you want to connect online or not, he sometimes by mistake he press yes and it freezes but if he select no it works ok as far as i know i have played 4 hours already everything looks good.

**Comment by Reisyukaku** [comment]
Yea theres a but in fs_mitm. If you have more than 7 DLC it will crash. You can just remove the fs_mitm.kip from the SD if you dont plan on using layered fs with that game.

**Comment by vaccarieli** [comment]
So if i just removed that problem solved ? Or  am i still have to uninstall 2 Dlc's, so it can work fine?

**Comment by Reisyukaku** [comment]
removing it should solve the problem at the expense of a feature you probably wont use lol

**Comment by vaccarieli** [comment]
Thanks i have tried and it is working fine, i just removed what you said .

**Comment by neonsea** [comment]
Maybe fs_mitm should be opt in instead of opt out? Personally think that people who need it know what they're doing and can enable it easily.

**Comment by Reisyukaku** [comment]
I might do that next release @neonsea

**Comment by vaccarieli** [comment]
There might be a lot more features or bugs to fix than the layer, just saying :)
