### ISSUE TITLE
NBA 2k18 is frozen from the start.

### ISSUE THREAD

**Issue by Expectro809** [Reisyukaku/ReiNX#40]
Please I need help. Every time I start the game it is frozen in the Nintendo icons and I have to reboot the console fiercely. 
I'm waiting for your answer soon. Thank you.

**Comment by neonsea** [comment]
What sigpatches have you enabled?

**Comment by HeroMines** [comment]
The real question should be why is he trying to play 2k18?
I mean, is that game like broken on the Nintendo Switch or something?

**Comment by Expectro809** [comment]
I have solved it. just delete the file "fs_mitm.kip" and it worked for me. Thank you.
