### ISSUE TITLE
QUESTION: What does fs_mitm.kip sigpatch do?

### ISSUE THREAD

**Issue by sandhoners123** [Reisyukaku/ReiNX#41]
Do I need the fs_mitm sigpatch to play cdnsp downloaded backup games or xci dumped backup games. Because if i don't, I will remove that kip so that I can prevent crashes due to it

**Comment by vaccarieli** [comment]
It is only a layer implementation, if you only use nsp games there is no reason to have it, i already removed it as Reinx told me to, and havent had more issues since then.

**Comment by neonsea** [comment]
If you don't know what it's for, you probably don't need it. IMHO, fs_mitm should be changed to opt-in.

**Comment by NekoNoor** [comment]
closing because questions don't belong in the github issues
