### ISSUE TITLE
i can't lunch original cartridge

### ISSUE THREAD

**Issue by angelmarlboro** [Reisyukaku/ReiNX#43]
like a tittle says, when i boot with ReiNX i can´t play original cartridge.
Thanks and Good Work

**Comment by noahc3** [comment]
Check ReiNX folder on your SD card and remove the nogc file if it's there.

**Comment by ApolloJustice** [comment]
it deliberately disables the game card slot to prevent a GC firmware update
if you used ChoiDujour to upgrade from a firmware lower than 4.0.0 to
something more recent than 4.0.0.

**Comment by angelmarlboro** [comment]
People, thanks very much. it´s works right now. now i can use my old cartridge
