### ISSUE TITLE
FS drivers are garbage. Nintendo plz

### ISSUE THREAD

**Issue by Reisyukaku** [Reisyukaku/ReiNX#44]
Some games (cart and digital) randomly shutoff the console. No error or anything. Can't seem to find a surefire way to trigger it. FS patches are suspect though.

**Comment by addictedgmr** [comment]
LayeredFS kip does not seem to affect it.

**Comment by Reisyukaku** [comment]
Worth noting i havent had those crashes in a while. Might have been SD corruption.
