### ISSUE TITLE
Silent launch

### ISSUE THREAD

**Issue by HowManyNamesHaveBeenTaken** [Reisyukaku/ReiNX#57]
Not actually an issue, but having a way to launch Reinx without seeing the small text at bootup would be nice.  Either a launch option or an alternative RCM payload if its coming from the bin. Thanks for the CFW!

**Comment by neonsea** [comment]
This is already the default behaviour since https://github.com/Reisyukaku/ReiNX/commit/2cc51b5cfe3d85fbbee3b79ba9f5cf4bc660f40c

Only booting while holding VOL- should display text. Update your ReiNX.

**Comment by HowManyNamesHaveBeenTaken** [comment]
Am using the latest build as of Sept. 11th, just started using ReiNX today. Still get text at bootup.

**Comment by neonsea** [comment]
That means that the ReiNX.bin on your SD is still an old build. Delete that file or update using the toolkit.

**Comment by HowManyNamesHaveBeenTaken** [comment]
There was no ReiNX.bin on my SD card, thought it was just a RCM payload. Just put the latest one on there and still get text.

**Comment by neonsea** [comment]
🤔

This shouldn't happen at all. What happens if you boot ReiNX while holding volume down, exactly the same behaviour? Or something else?

**Comment by HowManyNamesHaveBeenTaken** [comment]
Oh, that is a weird way to handle it, alright. Thanks for the help.
