### ISSUE TITLE
6.0 sleep/wake issue

### ISSUE THREAD

**Issue by sachaw** [Reisyukaku/ReiNX#58]
Running latest build, system on 6.0, once booted, if the power button is pressed, it goes to sleep but will no wake.

**Comment by dothackjhe** [comment]
![capture](https://user-images.githubusercontent.com/18740174/45791858-06482680-bcbe-11e8-8a8c-6f09adc739a8.JPG)

**Comment by Reisyukaku** [comment]
fix'd a4f171dcd975a7cba296f51c77bc41ae87d36e98
