### ISSUE TITLE
Unusable downloadable content: MODDED game

### ISSUE THREAD

**Issue by jkid291** [Reisyukaku/ReiNX#60]
I have been playing BOTW using the linkle mods (player model/armor, voice patch, and the title menu mods) and it works fine on atmosphere, on ReiNX i can play with the mods and all seems to be fine it plays with all of them but when I go to launch it it says..."
Unusable downloadable content was found.

Please connect to the Internet to check for more
information,
                        [Start Software]
[Cancel]                                        [Check]
"
If I hit Start Software it launches just fine and plays with the mods as far as I have tested. I thought I would bring this up and just say it does this, it does not do this on atmosphere so I figure its a problem, albeit a small one.
(Info on mod install. Files copied from the atmosphere\title\ directory. File name (title id) 01007EF00011E000 (Zelda: Breath of the Wild))

**Comment by Reisyukaku** [comment]
I use linkle mod all the time and that's never happened here.

**Comment by neonsea** [comment]
"Works on my machine 🤷“

😂
