### ISSUE TITLE
SleepMode breaks on 6.0 with svc debug kern patch

### ISSUE THREAD

**Issue by Reisyukaku** [Reisyukaku/ReiNX#63]
Need to look into why this is a think.

**Comment by angelmarlboro** [comment]
in 1.7 version works fine? or i need to do something else?

**Comment by Reisyukaku** [comment]
debug patch is optional as of cefc17432c593e8f749342bfbe0708b562eb2051
so if you have a file called 'debug' in /ReiNX it'll activate it.. similar to how the nogc patch works.. of course though activating it on 6.0 will break sleep mode because of some new checks in secmon i think.
