### ISSUE TITLE
Idea: Reinx's own fw upgrade function

### ISSUE THREAD

**Issue by khnoize** [Reisyukaku/ReiNX#72]
So, since just booting cfw itself would get the superban flag. The only way to update fw for cfw users are only a certain homebrew. And since this certain homebrew developer seems to not having a good relationship with reinx, I'm just thinking that having this functionality at reinx itself would be very great addition.

**Comment by Reisyukaku** [comment]
I dont think I follow.. I just update via system settings lol. Never had to use ChodeDigorno or whatever.

**Comment by khnoize** [comment]
Um, okay. I'm actually haven't tried yet, but I heard that even just booting cfw right now would means superban, so, no fw upgrade. But since you still use it, then that's not true right?

**Comment by Reisyukaku** [comment]
You're gonna get banned tampering with the system in any way.. so updating via nca installs or whatever isnt gonna save you. As soon as you hit online, you'll be flagged. Being constantly offline is basically no different than just being banned lol. Either way, Raj being salty shouldnt effect its usage with rnx though.

**Comment by khnoize** [comment]
@Reisyukaku I know, so basically, we ReiNX users are "already banned" (since (offline/banned) == no official nintendo services), and no more official system fw updates in the future, right? I was just wondering if it's great idea if ReiNX have its own fw updates tool since Raj being salty. Either way it's ok, we probably just would be have to use the existing tool and continue using ReiNX. Anyway, thank you for your responses.

**Comment by Reisyukaku** [comment]
There are ways to update even if banned but i have to see if i can streamline that

**Comment by khnoize** [comment]
Thanks, It would be great if this does come true one day. Though probably there are more immediate priorities than this for Reinx, hence it's just an idea.

**Comment by Multimegamander** [comment]
@Reisyukaku how long do I cook a ChodeDigorno for, senpai?
