### ISSUE TITLE
Idea: Control switch fan speeds

### ISSUE THREAD

**Issue by noisenstatic** [Reisyukaku/ReiNX#74]
Not sure if it is possible and how far are we able to control hardware atm. It would be great to control fan speeds at least while docked.

**Comment by gr3ger** [comment]
Might be a pretty dangerous option if the user who lowers fan speed isn't aware of how heating can damage the system.

**Comment by Reisyukaku** [comment]
Yea thats what i was thinking.. ill close for now since its not really on the drawing board anyways.
