### ISSUE TITLE
6.1.0 (possibly) breaks AutoRCM

### ISSUE THREAD

**Issue by spoonh** [Reisyukaku/ReiNX#79]
Updated to 6.1.0 while using AutoRCM, my switch does not boot into AutoRCM anymore and disabling/re-enabling auto rcm does not seem to do anything. No idea if i'm the only one with this occurrence.

**Comment by Faerye0** [comment]
Same problem here

**Comment by noahc3** [comment]
OP said disabling/re-enabling doesn't work.

**Comment by Reisyukaku** [comment]
Because they're probably enabling and disabling again.. just do it once. All autorcm does is write to the RSA mod on the BCT in nand. It literally bricks your nand forcing the system into RCM mode. lol

**Comment by spoonh** [comment]
> Because they're probably enabling and disabling again.. just do it once. All autorcm does is write to the RSA mod on the BCT in nand. It literally bricks your nand forcing the system into RCM mode. lol

This works, wasn't paying enough attention when i did this the first time i guess.
Thanks for your help.

**Comment by neonsea** [comment]
Great stuff

**Comment by spoonh** [comment]
Having this issue again, switch is essentially in "bricked state" after disable/reenable but is recognized as Nintendo Switch rather than 'APX'. Any ideas?

**Comment by Reisyukaku** [comment]
uhh try fully powering it off (holding power for 20 seconds) and turn it on?

**Comment by spoonh** [comment]
> uhh try fully powering it off (holding power for 20 seconds) and turn it on?

that works, but i have to do this every time i turn the console off now. eh, i'll just deal with it i guess.
