### ISSUE TITLE
Sysmodules dont boot

### ISSUE THREAD

**Issue by Reisyukaku** [Reisyukaku/ReiNX#84]
Title.
original code does atmo version check and booting depends a little on that i think, mixed with kips depending on each other.

**Comment by JamePeng** [comment]
Rei, I had tested. when the four kips was placed in the sysmodules folder, they are working fine. 
And I try to separate them like  your makefile with two folder, and sysmodules was not boot normally! you can check the code like about .dis folder execute.

**Comment by Reisyukaku** [comment]
fixed as of bcfb58dcba87d49103725216f67572d2c8c2bed8
