### ISSUE TITLE
Compression for NAND dumping

### ISSUE THREAD

**Issue by Warfields** [Reisyukaku/ReiNX#86]
The longest part of the NAND dump is the disk transfer, Since all of the dump files are ~3 Gb is it possible to load it into the Switch's ram and then run compression on it before saving to the SD? Just by using a zip compression i was able to reduce the 30Gb dump down to 604Mb after it was transfered to my machine, this would greatly increase the speed of the NAND dump.

**Comment by haxxey** [comment]
NAND dumping is included in the ReiNX Toolkit, not ReiNX itself - you should post the issue on its issues page https://github.com/Reisyukaku/ReiNXToolkit/issues

**Comment by neonsea** [comment]
NAND dumping is included in the ReiNX Toolkit, not ReiNX itself - you should post the issue on its issues page https://github.com/Reisyukaku/ReiNXToolkit/issues

**Comment by Warfields** [comment]
> NAND dumping is included in the ReiNX Toolkit, not ReiNX itself - you should post the issue on its issues page https://github.com/Reisyukaku/ReiNXToolkit/issues

Thanks I will do!
