### ISSUE TITLE
Still poorly / not compatible with LayeredFS? 

### ISSUE THREAD

**Issue by dothackjhe** [Reisyukaku/ReiNX#87]
In light of the recently-released Pokemon Let's Go Eevee / Pikachu which, like mainstream Pokemon titles, is modded to enhance gameplay experience, the LayeredFS feature of a jailbroken Switch remains as significant as ever. The problem, however, is that the said feature does not seem too compatible with ReiNX, even at its current latest version (1.7.1). 

Or am I just wrong?

**Comment by neonsea** [comment]
Once I get a proper dev setup working with an emulator, I will tackle this issue, among with other issues that ReiNX has had with the most recent firmwares. However, currently with no actual hardware I can't properly work on this. Sorry about that.

**Comment by Reisyukaku** [comment]
I've wrote something in the discord about it if you're there.. if not, then long story short I'm working on a few things and in the meantime you can always use the secmon override feature to use exosphere with newest kips

**Comment by Reisyukaku** [comment]
fixed as of bcfb58dcba87d49103725216f67572d2c8c2bed8

**Comment by dothackjhe** [comment]
I'm not too active at anywhere in Discord, unless I'm looking for something. I guess I will just wait for the next major update with ReiNX.

**Comment by Reisyukaku** [comment]
Well the commit is there if you're able to  compile but im still typing up some loose ends before a new release

**Comment by dothackjhe** [comment]
I'll probably just wait for the next major update.
