### ISSUE TITLE
problem: nintendo switch 6.2 update

### ISSUE THREAD

**Issue by GamingKingKKu** [Reisyukaku/ReiNX#88]
all CFWs are broken for this version.

**Comment by crdnl** [comment]
Small update: 6.2.0 updated key generation

new keys posted https://twitter.com/elmirorac/status/1066106288747237377

**Comment by Jacoby6000** [comment]
Those are key hashes, not the actual keys.  Those are being kept under wraps at the moment.

**Comment by ALANARIAS** [comment]
Does anyone know when the new reinx update will come out?

Will it be a long or short time?

**Comment by Reisyukaku** [comment]
Not long

**Comment by QuackerJ4ck** [comment]
Rei do you know how long exactly? I'm sorry I just really wanna play the new smash I really appreciate all the work you've done for us

**Comment by crdnl** [comment]
@QuackerJ4ck Then go preorder the game. It will run on FW 5.1.0 and up without issue, you just can't play online.

**Comment by QuackerJ4ck** [comment]
Wait how does that work would I have to downgrade my firmware?

**Comment by Jacoby6000** [comment]
Nobody knows how long. If you want cfw on 6.2 you need to wait. If you’re currently on 6.2 and you want CFW now, you need to downgrade.

**Comment by Reisyukaku** [comment]
We're shooting for this weekend.

**Comment by ALANARIAS** [comment]
This weekend, will the update come?

**Comment by jamescastells** [comment]
Hey, guys! Since atmosphere was updated, is that good news for Reinx? By the way, fantastic work!

**Comment by balika011** [comment]
Weekend is over.
Where is the update?

**Comment by bell07** [comment]
ReiNX is open source, if Rei is not fast enough for you, get the source, hack the 6.2 and release the awaiting update. Do not forget to set up a pull request.  ;-)

**Comment by piratesephiroth** [comment]
I guess they missed the shot

**Comment by tmargemZ** [comment]
I Just Hope It realease soon, bought my switch yesterday played 30 mins of Kirby then accidentaly update to 6.2... shit happens

**Comment by Nekxes** [comment]
> I Just Hope It realease soon, bought my switch yesterday played 30 mins of Kirby then accidentaly update to 6.2... shit happens

You still can use atmosphere to play any NSP games/app !

**Comment by VersatileNinja** [comment]
It's done when its done. No pressure. Take your time team!

**Comment by HappyVideoGameNerd** [comment]
Seriously...
It's fine to be excited, and even to wonder about progress.  But the man behind this doesn't owe us an exactly release date.  He doesn't even owe us the firmware at all.  He's doing it to be a bro.  

So chill out, and ease up on the "are we there yet"s.  Less gimme-gimme and more gratitude.  

It'll be done when it's done.  I'm excited too, but spamming the board with "release plz" only makes people mad.  And considering this is a project for little to know personal gain for the devs, we should really avoid being ungrateful.  

So to everyone involved in 6.2 and the work that went before - thanks.  We appreciate it.

**Comment by Romeosote** [comment]
Gracias reí confiamos en ti

**Comment by Chara-Reborn** [comment]
Shouldn't this be marked as closed? 🤔
