### ISSUE TITLE
Homebrew menu

### ISSUE THREAD

**Issue by MexyACJ** [Reisyukaku/ReiNX#89]
It doesn't let me Boot up the menu just in ReiNX

**Comment by noahc3** [comment]
You need Title 010000000000100D.zip from https://reinx.guide

**Comment by Reisyukaku** [comment]
The 100D files arent required as of 21098658d37578d40279bb0e4ddc691e2d4bd7ad
since you can use the hbl.nsp instead. When we create a release we'll update the guide.
