### ISSUE TITLE
cant use maximum allocation on exfat

### ISSUE THREAD

**Issue by masterspike52** [Reisyukaku/ReiNX#9]
ive deduced that when you use the max allocation size on exfat formatted sd cards it decides it cant init the sd card

**Comment by Reisyukaku** [comment]
You should use default allocation. Also I think this might be an issue with hekate's hwinit.

**Comment by Reisyukaku** [comment]
Updated sdmmc as of 59bd5dde19b2a68ffc0573f3901e17700b204749
give it a try

**Comment by Reisyukaku** [comment]
I think people said it still doesnt work so..
