### ISSUE TITLE
Implement a way to bypass Nintendo ban checks

### ISSUE THREAD

**Issue by HarleyPato** [Reisyukaku/ReiNX#90]
Since nobody was interested in it, I thought a bounty would make things easier and would motivate the dev to work on it.

We could start bypassing games that don't require Nintendo servers like Fortnite or Minecraft (and eventually a global unban).

I would personally add 5$ but if you guys want to contribute, then you're welcome!

**Comment by Aida-Enna** [comment]
Is there a bounty already made?

**Comment by HarleyPato** [comment]
Here: https://www.bountysource.com/issues/66595962-implement-a-way-to-bypass-nintendo-ban-checks
