### ISSUE TITLE
Boot problem on 2.0

### ISSUE THREAD

**Issue by jlozes** [Reisyukaku/ReiNX#95]
Hi,

I've tried the 2.0 release but it doesn't want to boot on my 6.1.0 console, the logo of the CFW is displayed and just after my console reboot to RCM (auto-RCM activated).

I have copied the "ReiNX" folder on my SD root, copied the "010000000000100D" folder on my "ReiNX/titles" folder (also tried with the "hbl.nsp" file on "ReiNX" folder) and I have used the last payload's version.

Am I missing something?

Thanks.

**Comment by Reisyukaku** [comment]
redownload the release. There was a quick fix added as of an hour ago.
